---
- name: Create a new VPC
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC
      include_vars: varsetup/myvpc

    - name: create my new VPC with dedicated tenancy and a couple of tags
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tags:
          module: My New VPC
          this: works
        tenancy: default
        state: "{{state}}"
      register: myvpc
    
    - name: Display the myPVC output
      debug:
        var: myvpc
   
    - name: Display the myPVC output
      debug:
        var: myvpc

    - name: Create Public Subnet 1 in Zone 1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ myvpc.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr_block: "{{ PubSub1Cidr }}"
        map_public: yes
        tags:
           Name: myVPC-publicsub1
        register: mypubsub1_out

